from smartmoney.models.signal import Signal


class SignalRepository:
    """
    Stores the latest signals generated by the scanners.
    """

    def __init__(self):

        self._signals: list[Signal] = []

    def replace(self, signals: list[Signal]) -> None:
        """
        Replace repository content with latest scan.
        """

        self._signals = list(signals)

    def add(self, signal: Signal) -> None:

        self._signals.append(signal)

    def all(self) -> list[Signal]:

        return list(self._signals)

    def clear(self) -> None:

        self._signals.clear()

    def count(self) -> int:

        return len(self._signals)